# Generated by Django 4.1.5 on 2023-01-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_item_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tatal',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
