# Generated by Django 4.1.5 on 2023-01-16 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_tatal_order_tatol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tatol',
            new_name='total',
        ),
    ]
